### ISSUE TITLE
20182.20で must be blittableでエラーになります。

### ISSUE THREAD

**Issue by ishiiyuki** [edom18/CurlNoise-unity#1]
ArgumentException: CurlNoiseSample.Particle type used in ComputeBuffer.SetData(array) must be blittable
UnityEngine.ComputeBuffer.SetData (System.Array data) (at C:/buildslave/unity/build/artifacts/generated/bindings_old/common/Core/ComputeShaderBindings.gen.cs:129)
CurlNoiseSample.CurlParticle.Initialize () (at Assets/CurlNoise/Scripts/CurlParticle.cs:386)
CurlNoiseSample.CurlParticle.Start () (at Assets/CurlNoise/Scripts/CurlParticle.cs:148)

こんなの出たので調べたんですけど
Particleのstructで　boolのactiveで怒られてるみたいでした。
ざっと見た感じ使ってない感じだったのでコメントアウトしたら動いたんで
情報共有でこちらに書き込みました。

**Comment by edom18** [comment]
コメントありがとうございます！　Macだと怒られるようで、こちら修正しておきます。

**Comment by edom18** [comment]
こちら修正しました！
